import Script from "next/script";

export default function Head() {
  return (
    <>
      <title>MyPost</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <Script
        src="https://kit.fontawesome.com/b7eb7b6f40.js"
        crossOrigin="anonymous"
      />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
